### ISSUE TITLE
Extract 2020 Stories

### ISSUE THREAD

**Issue by vukosim** [dsfsi/vukuzenzele-nlp#14] opened 2022-12-06 07:21 UTC
#### Description
Extract the 2022 stories from the PDFs and make them ready. 

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Run extraction pipeline to interim
- [ ] Clean up interim to processed
- [ ] Commit, do a pull request

**Comment by lastrucci01** [comment] 2023-08-14 07:40
Is this a duplicate of #15?

**Closed** 2024-03-26 08:22 UTC
Labels: enhancement
